### ISSUE TITLE
[Bug]: v3.0.0-rc0 invalid link path for pnpm link: to workspace package

### ISSUE THREAD

**Issue by matthewjh** [aspect-build/rules_js#2686]
### What happened?

I have an internal project with...

pnpm-workspace.yaml
```
packages:
  - js/node-loader/tests
 ```

js/node-loader/tests/package.json
```
{
  "name": "node-loader-test",
  "version": "1.0.0",
  "description": "",
  "private": true,
  "dependencies": {
    "@tw/pkg-a": "link:pkg-a",
    "@tw/pkg-b": "link:pkg-b",
    "@tw/pkg-c": "link:pkg-c",
    "@tw/pkg-d": "link:pkg-d"
  }
}
```

js/node-loader/tests/pkg-a/BUILD (etc. for pkg-b through -d)
```
load("@aspect_rules_js//npm:defs.bzl", "npm_link_package", "npm_package")

npm_package(
    name = "pkg",
    srcs = glob(["**/*"]),
    visibility = ["//:__subpackages__"],
)

```

In pnpm and rules_js 2.9.2 this worked fine, but since upgrading to 3.0.0-rc0 the following error is thrown:

```
        File "/Users/mhill/bazel/895e0b2e8d099c89c1a2308f48d6ff75/external/aspect_rules_js+/npm/extensions.bzl", line 64, column 39, in _npm_extension_impl
                _npm_translate_lock_bzlmod(module_ctx, attr, exclude_package_contents_config, replace_packages)
        File "/Users/mhill/bazel/895e0b2e8d099c89c1a2308f48d6ff75/external/aspect_rules_js+/npm/extensions.bzl", line 112, column 34, in _npm_translate_lock_bzlmod
                state = parse_and_verify_lock(module_ctx, attr.name, attr)
        File "/Users/mhill/bazel/895e0b2e8d099c89c1a2308f48d6ff75/external/aspect_rules_js+/npm/private/npm_translate_lock.bzl", line 378, column 41, in parse_and_verify_lock
                state = npm_translate_lock_state.new(rctx_name, rctx, attr)
        File "/Users/mhill/bazel/895e0b2e8d099c89c1a2308f48d6ff75/external/aspect_rules_js+/npm/private/npm_translate_lock_state.bzl", line 503, column 10, in _new
                _init(priv, rctx, attr)
        File "/Users/mhill/bazel/895e0b2e8d099c89c1a2308f48d6ff75/external/aspect_rules_js+/npm/private/npm_translate_lock_state.bzl", line 45, column 23, in _init
                _load_lockfile(priv, rctx, attr, rctx.path(attr.pnpm_lock), is_windows)
        File "/Users/mhill/bazel/895e0b2e8d099c89c1a2308f48d6ff75/external/aspect_rules_js+/npm/private/npm_translate_lock_state.bzl", line 412, column 99, in _load_lockfile
                importers, packages, pnpm_patched_dependencies, lock_parse_err = pnpm.parse_pnpm_lock_json(
        File "/Users/mhill/bazel/895e0b2e8d099c89c1a2308f48d6ff75/external/aspect_rules_js+/npm/private/pnpm.bzl", line 251, column 27, in _parse_pnpm_lock_json
                return _parse_lockfile(json.decode(content) if content else None, no_dev, no_optional, None)
        File "/Users/mhill/bazel/895e0b2e8d099c89c1a2308f48d6ff75/external/aspect_rules_js+/npm/private/pnpm.bzl", line 288, column 38, in _parse_lockfile
                importers = _convert_v9_importers(importers, snapshots, no_dev, no_optional)
        File "/Users/mhill/bazel/895e0b2e8d099c89c1a2308f48d6ff75/external/aspect_rules_js+/npm/private/pnpm.bzl", line 156, column 68, in _convert_v9_importers
                dependencies = _convert_pnpm_v9_importer_dependency_map(importers, snapshots, import_path, importer.get("dependencies", {})),
        File "/Users/mhill/bazel/895e0b2e8d099c89c1a2308f48d6ff75/external/aspect_rules_js+/npm/private/pnpm.bzl", line 132, column 21, in _convert_pnpm_v9_importer_dependency_map
                fail(msg)
Error in fail: Import @tw/pkg-a (link:pkg-a) from project 'js/node-loader/tests' has invalid link path: js/node-loader/tests/pkg-a
```

Changing pnpm-workspace.yaml from
```
packages:
  - js/node-loader/tests
 ```

pnpm-workspace.yaml
```
packages:
  - js/node-loader/tests/**
 ```

Seems to resolve it, but I assume this is a regression given the support previously and under pnpm

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

Language(s) and/or frameworks involved:

### How to reproduce

```shell

```

**Comment by matthewjh** [comment]
BTW @jbedard getting this error from rules_esbuild with rules_js 3.0.0-rc0... possible to push a new version there in case I can find some more bugs during the RC?
```
ERROR: /Users/mhill/bazel/895e0b2e8d099c89c1a2308f48d6ff75/external/aspect_rules_js+/npm/private/npm_import.bzl:1214:5: Traceback (most recent call last):
        File "/Users/mhill/bazel/895e0b2e8d099c89c1a2308f48d6ff75/external/aspect_rules_esbuild+/esbuild/extensions.bzl", line 38, column 36, in _toolchain_extension
                esbuild_register_toolchains(
        File "/Users/mhill/bazel/895e0b2e8d099c89c1a2308f48d6ff75/external/aspect_rules_esbuild+/esbuild/repositories.bzl", line 127, column 15, in esbuild_register_toolchains
                npm_import(
        File "/Users/mhill/bazel/895e0b2e8d099c89c1a2308f48d6ff75/external/aspect_rules_js+/npm/repositories.bzl", line 17, column 16, in npm_import
                _npm_import(
        File "/Users/mhill/bazel/895e0b2e8d099c89c1a2308f48d6ff75/external/aspect_rules_js+/npm/private/npm_import.bzl", line 1214, column 5, in npm_import
                def npm_import(
Error: npm_import() missing 1 required positional argument: exclude_package_contents_presets
```

**Comment by jbedard** [comment]
https://github.com/aspect-build/rules_js/commit/6b9c9ef42aaca739e5a55b1eb92184214d03cee2 should fix the [issue for rules_esbuild](https://github.com/aspect-build/rules_js/issues/2686#issuecomment-3772734284) 👍

**Comment by jbedard** [comment]
For the pnpm issue... you're linking to a directory that is not a project in your workspace? It seems pnpm supports that, what is the reason for doing that? I'll have to look into why rules_js got stricter in v3.

Does your workaround change the lockfile? Is there any issue doing this?

**Comment by jbedard** [comment]
FWIW here's the commit adding the assertion failing here: https://github.com/aspect-build/rules_js/commit/fc888cf161610c9142e7dd78dce672179f013000#diff-9cc048aa7d468377bc19c1381e35bf41471fdfec7901664f7e250e691e5be720R98-R101

**Comment by matthewjh** [comment]
Thanks @jbedard. I think this one is user error in that case and can be closed.

**Comment by jbedard** [comment]
If it's a valid lockfile then it could be considered a rules_js bug, or we can just declare it as a rules_js limitation. I have to investigate a bit more still.

Does this block you at all?

Is there a reason or advantage to linking to a directory that's not a project?

**Comment by matthewjh** [comment]
No, it doesn't block me.

And not particularly, though as someone who doesn't generally use pnpm workspaces nor want to, maybe there is a small advantage if I could not have to maintain package entries in pnpm-workspace.yaml at all.

BTW these are added as importers if I stick `/**` on the end of the packages entry:

```
  js/node-loader/tests/pkg-a: {}
  js/node-loader/tests/pkg-b: {}
  js/node-loader/tests/pkg-c: {}
  js/node-loader/tests/pkg-d: {}
```

**Comment by jbedard** [comment]
Do each of those `js/node-loader/tests/*` directories have a `package.json` and a `BUILD` with the target representing the package?

**Comment by matthewjh** [comment]
Yes

**Comment by jbedard** [comment]
I think #2691 would fix this, and is mainly just deleting code which is nice. So if it also aligns with pnpm then I think it's worth doing.

I think this aligns with pnpm... linked directories that are not part of the pnpm workspace means they will get symlinked into `node_modules` based on the `package.json` `name` like usual but they will never have a `node_modules` directory themselves and you can't do `npm_link_all_packages()` on them...
